name: ci-cd
on:
  push:
    branches:
      - main
      - unlocked
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Download dependencies
        run: npm install
      - name: Test
        run: npm run test:unit
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy to ked-agenda
        uses: w9jds/firebase-action@master
        if: github.ref_name == 'main'
        with:
          args: deploy --only hosting:ked
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to unlocked
        uses: w9jds/firebase-action@master
        if: github.ref_name == 'unlocked'
        with:
          args: deploy --only hosting:unlocked
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_UNLOCKED }}
